# name: GPT Swift Lint

# on:
#   pull_request:
#     types: [opened, synchronize]

# jobs:
#   gpt-lint:
#     runs-on: macos-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Fetch all branches
#         run: git fetch --all

#       - name: Check out main branch
#         run: git checkout cicd_checks_integration

#       - name: Set up Swift
#         run: |
#           swift --version

#       - name: Run GPT Lint
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#         run: |
#           swift gpt_lint.swift
